#pragma once
#include "GLES.h"

void WRAP(glFogiv(GLenum pname, const GLint* params));
void WRAP(glLighti(GLenum light, GLenum pname, GLint param));
void WRAP(glLightiv(GLenum light, GLenum pname, const GLint* params));
void WRAP(glLightModeliv(GLenum pname, const GLint* params));

void WRAP(glVertexAttrib1d(GLuint index, GLdouble x));
void WRAP(glVertexAttrib1dv(GLuint index, const GLdouble* v));
void WRAP(glVertexAttrib1s(GLuint index, GLshort x));
void WRAP(glVertexAttrib1sv(GLuint index, const GLshort* v));
void WRAP(glVertexAttrib2d(GLuint index, GLdouble x, GLdouble y));
void WRAP(glVertexAttrib2dv(GLuint index, const GLdouble* v));
void WRAP(glVertexAttrib2s(GLuint index, GLshort x, GLshort y));
void WRAP(glVertexAttrib2sv(GLuint index, const GLshort* v));
void WRAP(glVertexAttrib3dv(GLuint index, const GLdouble* v));
void WRAP(glVertexAttrib3s(GLuint index, GLshort x, GLshort y, GLshort z));
void WRAP(glVertexAttrib3sv(GLuint index, const GLshort* v));
void WRAP(glVertexAttrib4d(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w));
void WRAP(glVertexAttrib4dv(GLuint index, const GLdouble* v));
void WRAP(glVertexAttrib4s(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w));
void WRAP(glVertexAttrib4sv(GLuint index, const GLshort* v));
void WRAP(glVertexAttrib4bv(GLuint index, const GLbyte* v));
void WRAP(glVertexAttrib4ubv(GLuint index, const GLubyte* v));
void WRAP(glVertexAttrib4iv(GLuint index, const GLint* v));
void WRAP(glVertexAttrib4uiv(GLuint index, const GLuint* v));
void WRAP(glVertexAttrib4usv(GLuint index, const GLushort* v));
void WRAP(glVertexAttrib4Nbv(GLuint index, const GLbyte* v));
void WRAP(glVertexAttrib4Nubv(GLuint index, const GLubyte* v));
void WRAP(glVertexAttrib4Nsv(GLuint index, const GLshort* v));
void WRAP(glVertexAttrib4Nusv(GLuint index, const GLushort* v));
void WRAP(glVertexAttrib4Niv(GLuint index, const GLint* v));
void WRAP(glVertexAttrib4Nuiv(GLuint index, const GLuint* v));
void WRAP(glVertexAttrib4Nub(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w));
void WRAP(glVertexAttribI1i(GLuint index, GLint x));
void WRAP(glVertexAttribI1iv(GLuint index, const GLint* v));
void WRAP(glVertexAttribI1ui(GLuint index, GLuint x));
void WRAP(glVertexAttribI1uiv(GLuint index, const GLuint* v));
void WRAP(glVertexAttribI2i(GLuint index, GLint x, GLint y));
void WRAP(glVertexAttribI2iv(GLuint index, const GLint* v));
void WRAP(glVertexAttribI2ui(GLuint index, GLuint x, GLuint y));
void WRAP(glVertexAttribI2uiv(GLuint index, const GLuint* v));
void WRAP(glVertexAttribI3i(GLuint index, GLint x, GLint y, GLint z));
void WRAP(glVertexAttribI3iv(GLuint index, const GLint* v));
void WRAP(glVertexAttribI3ui(GLuint index, GLuint x, GLuint y, GLuint z));
void WRAP(glVertexAttribI3uiv(GLuint index, const GLuint* v));
void WRAP(glVertexAttribI4bv(GLuint index, const GLbyte* v));
void WRAP(glVertexAttribI4sv(GLuint index, const GLshort* v));
void WRAP(glVertexAttribI4ubv(GLuint index, const GLubyte* v));
void WRAP(glVertexAttribI4usv(GLuint index, const GLushort* v));
void WRAP(glTexCoord1dv(const GLdouble* v));
void WRAP(glTexCoord1iv(const GLint* v));
void WRAP(glTexCoord1sv(const GLshort* v));
void WRAP(glTexCoord3dv(const GLdouble* v));
void WRAP(glTexCoord3iv(const GLint* v));
void WRAP(glTexCoord3sv(const GLshort* v));
void WRAP(glTexCoord4dv(const GLdouble* v));
void WRAP(glTexCoord4iv(const GLint* v));
void WRAP(glTexCoord4sv(const GLshort* v));
void WRAP(glRasterPos2sv(const GLshort* v));
void WRAP(glRasterPos3iv(const GLint* v));
void WRAP(glRasterPos3sv(const GLshort* v));
void WRAP(glRasterPos4iv(const GLint* v));
void WRAP(glRasterPos4sv(const GLshort* v));
void WRAP(glWindowPos2dv(const GLdouble* v));
void WRAP(glWindowPos2s(GLshort x, GLshort y));
void WRAP(glWindowPos2sv(const GLshort* v));
void WRAP(glWindowPos3dv(const GLdouble* v));
void WRAP(glWindowPos3i(GLint x, GLint y, GLint z));
void WRAP(glWindowPos3iv(const GLint* v));
void WRAP(glWindowPos3s(GLshort x, GLshort y, GLshort z));
void WRAP(glWindowPos3sv(const GLshort* v));
void WRAP(glEvalCoord1dv(const GLdouble* v));
void WRAP(glEvalCoord1fv(const GLfloat* v));
void WRAP(glEvalCoord2dv(const GLdouble* v));
void WRAP(glEvalCoord2fv(const GLfloat* v));
void WRAP(glMultiTexCoord1dv(GLenum texture, const GLdouble* v));
void WRAP(glMultiTexCoord1iv(GLenum texture, const GLint* v));
void WRAP(glMultiTexCoord1s(GLenum texture, GLshort s));
void WRAP(glMultiTexCoord1sv(GLenum texture, const GLshort* v));
void WRAP(glMultiTexCoord3dv(GLenum texture, const GLdouble* v));
void WRAP(glMultiTexCoord3i(GLenum texture, GLint s, GLint t, GLint r));
void WRAP(glMultiTexCoord3iv(GLenum texture, const GLint* v));
void WRAP(glMultiTexCoord3s(GLenum texture, GLshort s, GLshort t, GLshort r));
void WRAP(glMultiTexCoord3sv(GLenum texture, const GLshort* v));
void WRAP(glMultiTexCoord4dv(GLenum texture, const GLdouble* v));
void WRAP(glMultiTexCoord4i(GLenum texture, GLint s, GLint t, GLint r, GLint q));
void WRAP(glMultiTexCoord4iv(GLenum texture, const GLint* v));
void WRAP(glMultiTexCoord4s(GLenum texture, GLshort s, GLshort t, GLshort r, GLshort q));
void WRAP(glMultiTexCoord4sv(GLenum texture, const GLshort* v));
void WRAP(glSecondaryColor3b(GLbyte r, GLbyte g, GLbyte b));
void WRAP(glSecondaryColor3bv(const GLbyte* v));
void WRAP(glSecondaryColor3i(GLint r, GLint g, GLint b));
void WRAP(glSecondaryColor3iv(const GLint* v));
void WRAP(glSecondaryColor3s(GLshort r, GLshort g, GLshort b));
void WRAP(glSecondaryColor3sv(const GLshort* v));
void WRAP(glSecondaryColor3ubv(const GLubyte* v));
void WRAP(glSecondaryColor3ui(GLuint r, GLuint g, GLuint b));
void WRAP(glSecondaryColor3uiv(const GLuint* v));
void WRAP(glSecondaryColor3us(GLushort r, GLushort g, GLushort b));
void WRAP(glSecondaryColor3usv(const GLushort* v));
void WRAP(glGetVertexAttribdv(GLuint index, GLenum pname, GLdouble* params));
