GLINAPI void WRAP(glMatrixMode(GLenum mode));
GLINAPI void WRAP(glLoadIdentity());
GLINAPI void WRAP(glPushMatrix());
GLINAPI void WRAP(glPopMatrix());
GLINAPI void WRAP(glLoadMatrixf(const GLfloat* m));
GLINAPI void WRAP(glLoadMatrixd(const GLdouble *m));
GLINAPI void WRAP(glMultMatrixf(const GLfloat *m));
GLINAPI void WRAP(glMultMatrixd(const GLdouble *m));
GLINAPI void WRAP(glTranslatef(GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glTranslated(GLdouble x, GLdouble y, GLdouble z));
GLINAPI void WRAP(glScalef(GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glScaled(GLdouble x, GLdouble y, GLdouble z));
GLINAPI void WRAP(glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glRotated(GLdouble angle, GLdouble x, GLdouble y, GLdouble z));
GLINAPI void WRAP(glFrustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearVal, GLdouble farVal));
GLINAPI void WRAP(glFrustumf(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat nearVal, GLfloat farVal));
GLINAPI void WRAP(glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearVal, GLdouble farVal));
GLINAPI void WRAP(glOrthof(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat nearVal, GLfloat farVal));
GLINAPI void WRAP(glLoadTransposeMatrixf(const GLfloat *m));
GLINAPI void WRAP(glLoadTransposeMatrixd(const GLdouble *m));
GLINAPI void WRAP(glMultTransposeMatrixf(const GLfloat *m));
GLINAPI void WRAP(glMultTransposeMatrixd(const GLdouble *m));
