GLINAPI void WRAP(glMatrixMode(GLenum mode));
GLINAPI void WRAP(glLoadIdentity());
GLINAPI void WRAP(glPushMatrix());
GLINAPI void WRAP(glPopMatrix());
GLINAPI void WRAP(glLoadMatrixf(const GLfloat* m));
GLINAPI void WRAP(glMultMatrixf(const GLfloat *m));
GLINAPI void WRAP(glTranslatef(GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glScalef(GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
GLINAPI void WRAP(glFrustum(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearVal, GLdouble farVal));
GLINAPI void WRAP(glOrtho(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble nearVal, GLdouble farVal));
