#include "GLES.h"

void WRAP(glBegin(GLenum mode));
void WRAP(glEnd());
void WRAP(glColor3f(GLfloat red, GLfloat green, GLfloat blue));
void WRAP(glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
void WRAP(glColor4sv(const GLshort* v));
void WRAP(glTexCoord2f(GLfloat s, GLfloat t));
void WRAP(glVertex3f(GLfloat x, GLfloat y, GLfloat z));
void WRAP(glVertex3i(GLint x, GLint y, GLint z));
void WRAP(glVertex2f(GLfloat x, GLfloat y));
void WRAP(glVertex2i(GLint x, GLint y));
void WRAP(glBindTexture(GLenum target, GLuint texture));
void WRAP(glDrawRangeElementsBaseVertex(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, void *indices, GLint basevertex));
void WRAP(glClipPlane(GLenum plane, const GLdouble *equation));
void WRAP(glClipPlanef(GLenum plane, const GLfloat *equation));
void WRAP(glClearDepth(double value));
void WRAP(glDepthRange(double n, double f));
void WRAP(glVertexAttribLPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer));
void WRAP(glVertexAttrib3d(GLuint index, GLdouble x, GLdouble y, GLdouble z));
void WRAP(glMultiDrawArrays(GLenum mode, const GLint* first, const GLsizei* count, GLsizei drawcount));
void WRAP(glMultiDrawElements(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei drawcount));
void WRAP(glMultiDrawElementsBaseVertex(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei drawcount, const GLint* basevertex));
void WRAP(glShadeModel(GLenum mode));
void WRAP(glPolygonMode(GLenum face, GLenum mode));
void WRAP(glEnableClientState(GLenum array));
void WRAP(glDisableClientState(GLenum array));
void WRAP(glVertexPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glColorPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glNormalPointer(GLenum type, GLsizei stride, const void *ptr));
void WRAP(glLightf(GLenum light, GLenum pname, GLfloat param));
void WRAP(glLightfv(GLenum light, GLenum pname, const GLfloat *params));
void WRAP(glLightModelf(GLenum pname, GLfloat param));
void WRAP(glLightModelfv(GLenum pname, const GLfloat* params));
void WRAP(glLightModeli(GLenum pname, GLint param));
void WRAP(glMaterialf(GLenum face, GLenum pname, GLfloat param));
void WRAP(glMaterialfv(GLenum face, GLenum pname, const GLfloat *params));
void WRAP(glFogf(GLenum pname, GLfloat param));
void WRAP(glFogfv(GLenum pname, const GLfloat *params));
void WRAP(glFogi(GLenum pname, GLint param));
void WRAP(glLogicOp(GLenum opcode));
void WRAP(glClientActiveTexture(GLenum texture));
void WRAP(glTexEnvi(GLenum target, GLenum pname, GLint param));
void WRAP(glTexEnvf(GLenum target, GLenum pname, GLfloat param));
void WRAP(glTexEnvfv(GLenum target, GLenum pname, const GLfloat *params));
void WRAP(glColorMaterial(GLenum face, GLenum mode));
