#include "GLES.h"

void WRAP(glBegin(GLenum mode));
void WRAP(glEnd());
void WRAP(glColor3f(GLfloat r, GLfloat g, GLfloat b));
void WRAP(glColor4f(GLfloat r, GLfloat g, GLfloat b, GLfloat a));
void WRAP(glColor3b(GLbyte r, GLbyte g, GLbyte b));
void WRAP(glColor3d(GLdouble r, GLdouble g, GLdouble b));
void WRAP(glColor3i(GLint r, GLint g, GLint b));
void WRAP(glColor3s(GLshort r, GLshort g, GLshort b));
void WRAP(glColor3ub(GLubyte r, GLubyte g, GLubyte b));
void WRAP(glColor3ui(GLuint r, GLuint g, GLuint b));
void WRAP(glColor3us(GLushort r, GLushort g, GLushort b));
void WRAP(glColor4b(GLbyte r, GLbyte g, GLbyte b, GLbyte a));
void WRAP(glColor4d(GLdouble r, GLdouble g, GLdouble b, GLdouble a));
void WRAP(glColor4i(GLint r, GLint g, GLint b, GLint a));
void WRAP(glColor4s(GLshort r, GLshort g, GLshort b, GLshort a));
void WRAP(glColor4ub(GLubyte r, GLubyte g, GLubyte b, GLubyte a));
void WRAP(glColor4ui(GLuint r, GLuint g, GLuint b, GLuint a));
void WRAP(glColor4us(GLushort r, GLushort g, GLushort b, GLushort a));
void WRAP(glColor3bv(const GLbyte* v));
void WRAP(glColor3dv(const GLdouble* v));
void WRAP(glColor3fv(const GLfloat* v));
void WRAP(glColor3iv(const GLint* v));
void WRAP(glColor3sv(const GLshort* v));
void WRAP(glColor3ubv(const GLubyte* v));
void WRAP(glColor3uiv(const GLuint* v));
void WRAP(glColor3usv(const GLushort* v));
void WRAP(glColor4bv(const GLbyte* v));
void WRAP(glColor4dv(const GLdouble* v));
void WRAP(glColor4fv(const GLfloat* v));
void WRAP(glColor4iv(const GLint* v));
void WRAP(glColor4sv(const GLshort* v));
void WRAP(glColor4ubv(const GLubyte* v));
void WRAP(glColor4uiv(const GLuint* v));
void WRAP(glColor4usv(const GLushort* v));
void WRAP(glColor4sv_legacy(const GLshort* v));
void WRAP(glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz));
void WRAP(glNormal3b(GLbyte nx, GLbyte ny, GLbyte nz));
void WRAP(glNormal3d(GLdouble nx, GLdouble ny, GLdouble nz));
void WRAP(glNormal3i(GLint nx, GLint ny, GLint nz));
void WRAP(glNormal3s(GLshort nx, GLshort ny, GLshort nz));
void WRAP(glNormal3bv(const GLbyte* v));
void WRAP(glNormal3dv(const GLdouble* v));
void WRAP(glNormal3fv(const GLfloat* v));
void WRAP(glNormal3iv(const GLint* v));
void WRAP(glNormal3sv(const GLshort* v));
void WRAP(glVertex3f(GLfloat x, GLfloat y, GLfloat z));
void WRAP(glVertex2f(GLfloat x, GLfloat y));
void WRAP(glVertex2i(GLint x, GLint y));
void WRAP(glVertex3i(GLint x, GLint y, GLint z));
void WRAP(glVertex2d(GLdouble x, GLdouble y));
void WRAP(glVertex2s(GLshort x, GLshort y));
void WRAP(glVertex3d(GLdouble x, GLdouble y, GLdouble z));
void WRAP(glVertex3s(GLshort x, GLshort y, GLshort z));
void WRAP(glVertex4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w));
void WRAP(glVertex4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w));
void WRAP(glVertex4i(GLint x, GLint y, GLint z, GLint w));
void WRAP(glVertex4s(GLshort x, GLshort y, GLshort z, GLshort w));
void WRAP(glVertex2fv(const GLfloat* v));
void WRAP(glVertex2dv(const GLdouble* v));
void WRAP(glVertex2iv(const GLint* v));
void WRAP(glVertex2sv(const GLshort* v));
void WRAP(glVertex3fv(const GLfloat* v));
void WRAP(glVertex3dv(const GLdouble* v));
void WRAP(glVertex3iv(const GLint* v));
void WRAP(glVertex3sv(const GLshort* v));
void WRAP(glVertex4fv(const GLfloat* v));
void WRAP(glVertex4dv(const GLdouble* v));
void WRAP(glVertex4iv(const GLint* v));
void WRAP(glVertex4sv(const GLshort* v));
void WRAP(glTexCoord2f(GLfloat s, GLfloat t));
void WRAP(glTexCoord1f(GLfloat s));
void WRAP(glTexCoord1d(GLdouble s));
void WRAP(glTexCoord1i(GLint s));
void WRAP(glTexCoord1s(GLshort s));
void WRAP(glTexCoord2d(GLdouble s, GLdouble t));
void WRAP(glTexCoord2i(GLint s, GLint t));
void WRAP(glTexCoord2s(GLshort s, GLshort t));
void WRAP(glTexCoord3f(GLfloat s, GLfloat t, GLfloat r));
void WRAP(glTexCoord3d(GLdouble s, GLdouble t, GLdouble r));
void WRAP(glTexCoord3i(GLint s, GLint t, GLint r));
void WRAP(glTexCoord3s(GLshort s, GLshort t, GLshort r));
void WRAP(glTexCoord4f(GLfloat s, GLfloat t, GLfloat r, GLfloat q));
void WRAP(glTexCoord4d(GLdouble s, GLdouble t, GLdouble r, GLdouble q));
void WRAP(glTexCoord4i(GLint s, GLint t, GLint r, GLint q));
void WRAP(glTexCoord4s(GLshort s, GLshort t, GLshort r, GLshort q));
void WRAP(glTexCoord1fv(const GLfloat* v));
void WRAP(glTexCoord2fv(const GLfloat* v));
void WRAP(glTexCoord2dv(const GLdouble* v));
void WRAP(glTexCoord2iv(const GLint* v));
void WRAP(glTexCoord2sv(const GLshort* v));
void WRAP(glTexCoord3fv(const GLfloat* v));
void WRAP(glTexCoord4fv(const GLfloat* v));
void WRAP(glBindTexture(GLenum target, GLuint texture));
void WRAP(glDrawRangeElementsBaseVertex(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, void *indices, GLint basevertex));
void WRAP(glMultiDrawArrays(GLenum mode, const GLint* first, const GLsizei* count, GLsizei drawcount));
void WRAP(glMultiDrawElements(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei drawcount));
void WRAP(glMultiDrawElementsBaseVertex(GLenum mode, const GLsizei* count, GLenum type, const void* const* indices, GLsizei drawcount, const GLint* basevertex));
void WRAP(glClipPlane(GLenum plane, const GLdouble *equation));
void WRAP(glClipPlanef(GLenum plane, const GLfloat *equation));
void WRAP(glClearDepth(double value));
void WRAP(glDepthRange(double n, double f));
void WRAP(glVertexAttribLPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer));
void WRAP(glVertexAttrib3d(GLuint index, GLdouble x, GLdouble y, GLdouble z));
void WRAP(glShadeModel(GLenum model));
void WRAP(glPolygonMode(GLenum face, GLenum mode));
void WRAP(glEnableClientState(GLenum array));
void WRAP(glDisableClientState(GLenum array));
void WRAP(glVertexPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glColorPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const void *ptr));
void WRAP(glNormalPointer(GLenum type, GLsizei stride, const void *ptr));
void WRAP(glLightf(GLenum light, GLenum pname, GLfloat param));
void WRAP(glLightfv(GLenum light, GLenum pname, const GLfloat *params));
void WRAP(glLightModelf(GLenum pname, GLfloat param));
void WRAP(glLightModelfv(GLenum pname, const GLfloat* params));
void WRAP(glLightModeli(GLenum pname, GLint param));
void WRAP(glMaterialf(GLenum face, GLenum pname, GLfloat param));
void WRAP(glMaterialfv(GLenum face, GLenum pname, const GLfloat *params));
void WRAP(glMateriali(GLenum face, GLenum pname, GLint param));
void WRAP(glMaterialiv(GLenum face, GLenum pname, const GLint *params));
void WRAP(glFogf(GLenum pname, GLfloat param));
void WRAP(glFogfv(GLenum pname, const GLfloat *params));
void WRAP(glFogi(GLenum pname, GLint param));
void WRAP(glLogicOp(GLenum opcode));
void WRAP(glClientActiveTexture(GLenum texture));
void WRAP(glTexEnvi(GLenum target, GLenum pname, GLint param));
void WRAP(glTexEnvf(GLenum target, GLenum pname, GLfloat param));
void WRAP(glTexEnvfv(GLenum target, GLenum pname, const GLfloat *p));
void WRAP(glTexEnviv(GLenum target, GLenum pname, const GLint *params));
void WRAP(glColorMaterial(GLenum face, GLenum mode));
void WRAP(glArrayElement(GLint i));
void WRAP(glInterleavedArrays(GLenum format, GLsizei stride, const void* pointer));
void WRAP(glMultiTexCoord1f(GLenum t, GLfloat s));
void WRAP(glMultiTexCoord2f(GLenum t, GLfloat s, GLfloat r));
void WRAP(glMultiTexCoord3f(GLenum t, GLfloat s, GLfloat r, GLfloat q));
void WRAP(glMultiTexCoord4f(GLenum t, GLfloat s, GLfloat r, GLfloat q, GLfloat w));
void WRAP(glMultiTexCoord1d(GLenum t, GLdouble s));
void WRAP(glMultiTexCoord2d(GLenum t, GLdouble s, GLdouble r));
void WRAP(glMultiTexCoord3d(GLenum t, GLdouble s, GLdouble r, GLdouble q));
void WRAP(glMultiTexCoord4d(GLenum t, GLdouble s, GLdouble r, GLdouble q, GLdouble w));
void WRAP(glMultiTexCoord1i(GLenum t, GLint s));
void WRAP(glMultiTexCoord2i(GLenum t, GLint s, GLint r));
void WRAP(glMultiTexCoord2s(GLenum t, GLshort s, GLshort r));
void WRAP(glMultiTexCoord1fv(GLenum t, const GLfloat* v));
void WRAP(glMultiTexCoord2fv(GLenum t, const GLfloat* v));
void WRAP(glMultiTexCoord3fv(GLenum t, const GLfloat* v));
void WRAP(glMultiTexCoord4fv(GLenum t, const GLfloat* v));
void WRAP(glMultiTexCoord2dv(GLenum t, const GLdouble* v));
void WRAP(glMultiTexCoord2iv(GLenum t, const GLint* v));
void WRAP(glMultiTexCoord2sv(GLenum t, const GLshort* v));
void WRAP(glTexGenf(GLenum coord, GLenum pname, GLfloat param));
void WRAP(glTexGend(GLenum coord, GLenum pname, GLdouble param));
void WRAP(glTexGeni(GLenum coord, GLenum pname, GLint param));
void WRAP(glTexGenfv(GLenum coord, GLenum pname, const GLfloat* p));
void WRAP(glTexGendv(GLenum coord, GLenum pname, const GLdouble* p));
void WRAP(glTexGeniv(GLenum coord, GLenum pname, const GLint* p));
void WRAP(glPointParameterf(GLenum pname, GLfloat param));
void WRAP(glPointParameteri(GLenum pname, GLint param));
void WRAP(glPointParameterfv(GLenum pname, const GLfloat* p));
void WRAP(glPointParameteriv(GLenum pname, const GLint* p));
void WRAP(glSecondaryColorPointer(GLint size, GLenum type, GLsizei stride, const void* ptr));
void WRAP(glEdgeFlag(GLboolean flag));
void WRAP(glEdgeFlagv(const GLboolean* flag));
void WRAP(glEdgeFlagPointer(GLsizei stride, const void* ptr));
void WRAP(glPolygonStipple(const GLubyte* mask));
void WRAP(glGetPolygonStipple(GLubyte* mask));
void WRAP(glLineStipple(GLint factor, GLushort pattern));
void WRAP(glPixelZoom(GLfloat xfactor, GLfloat yfactor));
void WRAP(glPixelTransferf(GLenum pname, GLfloat param));
void WRAP(glPixelTransferi(GLenum pname, GLint param));
void WRAP(glPixelMapfv(GLenum map, GLsizei size, const GLfloat* v));
void WRAP(glPixelMapuiv(GLenum map, GLsizei size, const GLuint* v));
void WRAP(glPixelMapusv(GLenum map, GLsizei size, const GLushort* v));
void WRAP(glGetPixelMapfv(GLenum map, GLfloat* v));
void WRAP(glGetPixelMapuiv(GLenum map, GLuint* v));
void WRAP(glGetPixelMapusv(GLenum map, GLushort* v));
void WRAP(glDrawPixels(GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels));
void WRAP(glCopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type));
