//#define USE_MAP_FOR_SHADERS_DESC
#define MAX_VTX_PROG_ENV_PARAMS 96
#define MAX_VTX_PROG_LOC_PARAMS 96
#define MAX_FRG_PROG_ENV_PARAMS 24
#define MAX_FRG_PROG_LOC_PARAMS 24
#define MAX_ARB_ATTRIBUTES      16
#define MAX_ARB_MATRIX  8