//#define USE_MAP_FOR_SHADERS_DESC
#define MAX_COUNT_OF_SAVED_SHADERS 65536
#define MAX_COUNT_OF_SAVED_ARB_PROGS 65536
#define MAX_COUNT_OF_SAVED_TEXTURES 65536

#define MAX_VTX_PROG_ENV_PARAMS 96
#define MAX_VTX_PROG_LOC_PARAMS 96
#define MAX_FRG_PROG_ENV_PARAMS 24
#define MAX_FRG_PROG_LOC_PARAMS 24
#define MAX_ARB_ATTRIBUTES      16
#define MAX_ARB_MATRIX  8