void GLIN_Wrap_glClipPlane(GLenum plane, const GLdouble *equation);
void GLIN_Wrap_glDeletePrograms(GLsizei n, const GLuint *programs);
void GLIN_Wrap_glGetCompressedTexImage(GLenum target, GLint lod, GLvoid *img);
void GLIN_Wrap_glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void GLIN_Wrap_glTexCoord2f(GLfloat s, GLfloat t);
void GLIN_Wrap_glPolygonMode(GLenum face, GLenum mode);
void GLIN_Wrap_glPopAttrib();
void GLIN_Wrap_glPushAttrib(GLbitfield mask);
void GLIN_Wrap_glProgramString(GLenum target, GLenum format, GLsizei len, const GLvoid *string);
void GLIN_Wrap_glEnableClientState(GLenum array);
void GLIN_Wrap_glDisableClientState(GLenum array);
void GLIN_Wrap_glClientActiveTexture(GLenum texture);
void GLIN_Wrap_glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void GLIN_Wrap_glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void GLIN_Wrap_glProgramEnvParameters4fv(GLenum target, GLuint index, GLsizei count, const GLfloat *params);
void GLIN_Wrap_glEnableIndexed(GLenum target, GLuint index);
void GLIN_Wrap_glDisableIndexed(GLenum target, GLuint index);
void GLIN_Wrap_glGetBooleanIndexedv(GLenum target, GLuint index, GLboolean *data);
void GLIN_Wrap_glPopClientAttrib();
void GLIN_Wrap_glPushClientAttrib(GLbitfield mask);