#include "GLES.h"

GLuint WRAP(glGenLists(GLsizei range));
void WRAP(glNewList(GLuint list, GLenum mode));
void WRAP(glEndList());
void WRAP(glCallList(GLuint list));
void WRAP(glCallLists(GLsizei n, GLenum type, const GLvoid* lists));
void WRAP(glDeleteLists(GLuint list, GLsizei range));
GLboolean WRAP(glIsList(GLuint list));
void WRAP(glListBase(GLuint base));
void WRAP(glPushAttrib(GLbitfield mask));
void WRAP(glPopAttrib());
void WRAP(glPushClientAttrib(GLbitfield mask));
void WRAP(glPopClientAttrib());
void WRAP(glProgramEnvParameters4fv(GLenum target, GLuint index, GLsizei count, const GLfloat *params));
void WRAP(glEnableIndexed(GLenum target, GLuint index));
void WRAP(glDisableIndexed(GLenum target, GLuint index));
void WRAP(glGetBooleanIndexedv(GLenum target, GLuint index, GLboolean *data));
void WRAP(glGetCompressedTexImage(GLenum target, GLint lod, GLvoid *img));
void WRAP(glGetProgramiv(GLenum target,GLenum pname,GLint *params));
void WRAP(glGetIntegerv(GLenum pname, GLint* params));
void WRAP(glGetInteger64v(GLenum pname, GLint64* params));
void WRAP(glEnable(GLenum cap));
void WRAP(glDisable(GLenum cap));
GLboolean WRAP(glIsEnabled(GLenum cap));
void WRAP(glGetFloatv(GLenum pname, GLfloat* data));
void WRAP(glGetDoublev(GLenum pname, GLdouble* data));
void WRAP(glPixelStoref(GLenum pname, GLfloat param));
void WRAP(glAlphaFunc(GLenum func, GLfloat ref));
void WRAP(glPointSize(GLfloat size));
void WRAP(glLineWidth(GLfloat width));
void WRAP(glRasterPos2f(GLfloat x, GLfloat y));
void WRAP(glRasterPos2d(GLdouble x, GLdouble y));
void WRAP(glRasterPos2i(GLint x, GLint y));
void WRAP(glRasterPos2s(GLshort x, GLshort y));
void WRAP(glRasterPos3f(GLfloat x, GLfloat y, GLfloat z));
void WRAP(glRasterPos3d(GLdouble x, GLdouble y, GLdouble z));
void WRAP(glRasterPos3i(GLint x, GLint y, GLint z));
void WRAP(glRasterPos3s(GLshort x, GLshort y, GLshort z));
void WRAP(glRasterPos4f(GLfloat x, GLfloat y, GLfloat z, GLfloat w));
void WRAP(glRasterPos4d(GLdouble x, GLdouble y, GLdouble z, GLdouble w));
void WRAP(glRasterPos4i(GLint x, GLint y, GLint z, GLint w));
void WRAP(glRasterPos4s(GLshort x, GLshort y, GLshort z, GLshort w));
void WRAP(glRasterPos2fv(const GLfloat* v));
void WRAP(glRasterPos2dv(const GLdouble* v));
void WRAP(glRasterPos2iv(const GLint* v));
void WRAP(glRasterPos3fv(const GLfloat* v));
void WRAP(glRasterPos3dv(const GLdouble* v));
void WRAP(glRasterPos4fv(const GLfloat* v));
void WRAP(glRasterPos4dv(const GLdouble* v));
void WRAP(glWindowPos2f(GLfloat x, GLfloat y));
void WRAP(glWindowPos2d(GLdouble x, GLdouble y));
void WRAP(glWindowPos2i(GLint x, GLint y));
void WRAP(glWindowPos3f(GLfloat x, GLfloat y, GLfloat z));
void WRAP(glWindowPos3d(GLdouble x, GLdouble y, GLdouble z));
void WRAP(glWindowPos2fv(const GLfloat* v));
void WRAP(glWindowPos2iv(const GLint* v));
void WRAP(glWindowPos3fv(const GLfloat* v));
void WRAP(glBitmap(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte* bitmap));
void WRAP(glRectf(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2));
void WRAP(glRectd(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2));
void WRAP(glRecti(GLint x1, GLint y1, GLint x2, GLint y2));
void WRAP(glRects(GLshort x1, GLshort y1, GLshort x2, GLshort y2));
void WRAP(glRectfv(const GLfloat* v1, const GLfloat* v2));
void WRAP(glRectdv(const GLdouble* v1, const GLdouble* v2));
void WRAP(glRectiv(const GLint* v1, const GLint* v2));
void WRAP(glRectsv(const GLshort* v1, const GLshort* v2));
void WRAP(glSecondaryColor3f(GLfloat r, GLfloat g, GLfloat b));
void WRAP(glSecondaryColor3d(GLdouble r, GLdouble g, GLdouble b));
void WRAP(glSecondaryColor3ub(GLubyte r, GLubyte g, GLubyte b));
void WRAP(glSecondaryColor3fv(const GLfloat* v));
void WRAP(glSecondaryColor3dv(const GLdouble* v));
void WRAP(glFogCoordf(GLfloat coord));
void WRAP(glFogCoordd(GLdouble coord));
void WRAP(glFogCoordfv(const GLfloat* v));
void WRAP(glFogCoorddv(const GLdouble* v));
void WRAP(glDrawArrays(GLenum mode, GLint first, GLsizei count));
void WRAP(glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices));
void WRAP(glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices));
void WRAP(glDrawElementsBaseVertex(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex));
void WRAP(glHint(GLenum target, GLenum mode));
void WRAP(glAccum(GLenum op, GLfloat value));
void WRAP(glClearAccum(GLfloat r, GLfloat g, GLfloat b, GLfloat a));
void WRAP(glPassThrough(GLfloat token));
void WRAP(glSelectBuffer(GLsizei size, GLuint* buffer));
void WRAP(glFeedbackBuffer(GLsizei size, GLenum type, GLfloat* buffer));
GLint WRAP(glRenderMode(GLenum mode));
void WRAP(glInitNames());
void WRAP(glPushName(GLuint name));
void WRAP(glPopName());
void WRAP(glLoadName(GLuint name));
void WRAP(glMap1f(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat* points));
void WRAP(glMap1d(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble* points));
void WRAP(glMap2f(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat* points));
void WRAP(glMap2d(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble* points));
void WRAP(glMapGrid1f(GLint un, GLfloat u1, GLfloat u2));
void WRAP(glMapGrid1d(GLint un, GLdouble u1, GLdouble u2));
void WRAP(glMapGrid2f(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2));
void WRAP(glMapGrid2d(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2));
void WRAP(glEvalMesh1(GLenum mode, GLint i1, GLint i2));
void WRAP(glEvalMesh2(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2));
void WRAP(glEvalPoint1(GLint i));
void WRAP(glEvalPoint2(GLint i, GLint j));
void WRAP(glEvalCoord1f(GLfloat u));
void WRAP(glEvalCoord1d(GLdouble u));
void WRAP(glEvalCoord2f(GLfloat u, GLfloat v));
void WRAP(glEvalCoord2d(GLdouble u, GLdouble v));
void WRAP(glGetMapiv(GLenum target, GLenum query, GLint* v));
void WRAP(glGetMapfv(GLenum target, GLenum query, GLfloat* v));
void WRAP(glGetMapdv(GLenum target, GLenum query, GLdouble* v));
void WRAP(glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instances));
void WRAP(glGetPointerv(GLenum pname, void** params));
void WRAP(glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
void WRAP(glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
void WRAP(glGetBooleanv(GLenum pname, GLboolean* params));
void WRAP(glGetLightfv(GLenum light, GLenum pname, GLfloat* params));
void WRAP(glGetLightiv(GLenum light, GLenum pname, GLint* params));
void WRAP(glGetMaterialfv(GLenum face, GLenum pname, GLfloat* params));
void WRAP(glGetMaterialiv(GLenum face, GLenum pname, GLint* params));
void WRAP(glGetClipPlane(GLenum plane, GLdouble* equation));
void WRAP(glGetTexEnvfv(GLenum target, GLenum pname, GLfloat* params));
void WRAP(glGetTexEnviv(GLenum target, GLenum pname, GLint* params));
void WRAP(glGetTexGenfv(GLenum coord, GLenum pname, GLfloat* params));
void WRAP(glGetTexGendv(GLenum coord, GLenum pname, GLdouble* params));
void WRAP(glGetTexGeniv(GLenum coord, GLenum pname, GLint* params));
void WRAP(glTexImage1D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void* pixels));
void WRAP(glTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void* pixels));
void WRAP(glCopyTexImage1D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border));
void WRAP(glCopyTexSubImage1D(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width));
void WRAP(glFramebufferTexture1D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level));
void WRAP(glClampColor(GLenum target, GLenum clamp));
void WRAP(glPrioritizeTextures(GLsizei n, const GLuint* textures, const GLclampf* priorities));
GLboolean WRAP(glAreTexturesResident(GLsizei n, const GLuint* textures, GLboolean* residences));
void WRAP(glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, void* pixels));
void WRAP(glColorTable(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const void* table));
void WRAP(glColorTableParameterfv(GLenum target, GLenum pname, const GLfloat* p));
void WRAP(glColorTableParameteriv(GLenum target, GLenum pname, const GLint* p));
void WRAP(glCopyColorTable(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width));
void WRAP(glGetColorTable(GLenum target, GLenum format, GLenum type, void* table));
void WRAP(glGetColorTableParameterfv(GLenum t, GLenum p, GLfloat* v));
void WRAP(glGetColorTableParameteriv(GLenum t, GLenum p, GLint* v));
void WRAP(glColorSubTable(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const void* data));
void WRAP(glCopyColorSubTable(GLenum target, GLsizei start, GLint x, GLint y, GLsizei width));
void WRAP(glConvolutionFilter1D(GLenum t,GLenum i,GLsizei w,GLenum f,GLenum ty,const void* d));
void WRAP(glConvolutionFilter2D(GLenum t,GLenum i,GLsizei w,GLsizei h,GLenum f,GLenum ty,const void* d));
void WRAP(glConvolutionParameterf(GLenum t,GLenum p,GLfloat v));
void WRAP(glConvolutionParameterfv(GLenum t,GLenum p,const GLfloat* v));
void WRAP(glConvolutionParameteri(GLenum t,GLenum p,GLint v));
void WRAP(glConvolutionParameteriv(GLenum t,GLenum p,const GLint* v));
void WRAP(glCopyConvolutionFilter1D(GLenum t,GLenum i,GLint x,GLint y,GLsizei w));
void WRAP(glCopyConvolutionFilter2D(GLenum t,GLenum i,GLint x,GLint y,GLsizei w,GLsizei h));
void WRAP(glGetConvolutionFilter(GLenum t,GLenum f,GLenum ty,void* img));
void WRAP(glGetConvolutionParameterfv(GLenum t,GLenum p,GLfloat* v));
void WRAP(glGetConvolutionParameteriv(GLenum t,GLenum p,GLint* v));
void WRAP(glSeparableFilter2D(GLenum t,GLenum i,GLsizei w,GLsizei h,GLenum f,GLenum ty,const void* r,const void* c));
void WRAP(glGetSeparableFilter(GLenum t,GLenum f,GLenum ty,void* r,void* c,void* sp));
void WRAP(glHistogram(GLenum t,GLsizei w,GLenum i,GLboolean s));
void WRAP(glResetHistogram(GLenum t));
void WRAP(glGetHistogram(GLenum t,GLboolean r,GLenum f,GLenum ty,void* v));
void WRAP(glGetHistogramParameterfv(GLenum t,GLenum p,GLfloat* v));
void WRAP(glGetHistogramParameteriv(GLenum t,GLenum p,GLint* v));
void WRAP(glMinmax(GLenum t,GLenum i,GLboolean s));
void WRAP(glResetMinmax(GLenum t));
void WRAP(glGetMinmax(GLenum t,GLboolean r,GLenum f,GLenum ty,void* v));
void WRAP(glGetMinmaxParameterfv(GLenum t,GLenum p,GLfloat* v));
void WRAP(glGetMinmaxParameteriv(GLenum t,GLenum p,GLint* v));

void WRAP(glPrimitiveRestartIndex(GLuint index));
void WRAP(glProvokingVertex(GLenum mode));
void WRAP(glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instances));
void WRAP(glDrawElementsInstancedBaseVertex(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instances, GLint base));
